# Generated by Django 4.2.7 on 2024-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0002_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divname', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
