# Generated by Django 5.0 on 2024-01-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_employee',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
