# Generated by Django 5.0 on 2024-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0002_alter_department_employee_todate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees_photos/'),
        ),
    ]
